<template>
  <section class="lecture" id="l1" ref="rootEl">
    <div class="lecture-head">
      <span class="ltag">LECTURE 01 · FEB 16</span>
      <h2>Introduction to Robot Learning</h2>
      <p class="dek">Why the classical robotics pipeline hit a wall, why learning is the way through it, and the map of paradigms the rest of the course explores one by one.</p>
    </div>

    <div class="meta-strip">
      <span class="chip"><b>Prereqs</b> none — start here</span>
      <span class="chip"><b>Time</b> ~30 min</span>
      <span class="chip"><b>Watch first</b> the paradigm map (§1.3)</span>
    </div>
    <div class="callout miscon"><span class="co-label">Watch out for</span>
      <ul>
        <li>"Robot learning" is <em>not</em> "deep learning that happens to run on a robot" — the sequential, safety-critical, data-scarce setting changes which methods work.</li>
        <li>More learning/autonomy isn't automatically better; when the model is known, the classical pipeline (L2) often wins.</li>
      </ul>
    </div>

    <h3><span class="knum">1.1</span>The classical pipeline and where it breaks</h3>
    <p>Robotics worked for decades without learning. The classical recipe — <strong>sense → plan → act</strong> — perceives the world into an explicit state estimate (object poses, maps), plans a trajectory through it with model-based optimization, and executes with a feedback controller built on the dynamics equations from the Primer. This is how factory arms place millions of parts and how rockets land: when the environment is <em>structured</em>, instrumented, and modeled, classical methods are precise, verifiable, and unbeatable.</p>
    <p>The wall appears in <em>open</em> environments. Three compounding problems:</p>
    <ul>
      <li><strong>Perception is the bottleneck.</strong> Going from pixels to "the mug's 6D pose, its mass, its friction" is itself an unsolved estimation problem in clutter, glare, and occlusion. Hand-built pipelines are brittle exactly where modern vision (deep networks) is strong.</li>
      <li><strong>Contact-rich physics resists modeling.</strong> Inserting a plug, folding a shirt, walking on gravel — friction, deformation, impacts. Writing accurate equations per object and surface doesn't scale.</li>
      <li><strong>The long tail.</strong> Homes and hospitals are not factories: every scene is slightly different. Engineering each case by hand has unbounded cost; we need systems that <em>generalize</em> — which is precisely what statistical learning is for.</li>
    </ul>
    <p>Hence the course's premise: replace hand-derived components with <strong>functions learned from data</strong> — sometimes just perception, increasingly the entire sensor-to-motor mapping ("end-to-end").</p>

    <h3><span class="knum">1.2</span>What makes robot learning different from the ML you know</h3>
    <p>If learning works for images and language, why is robotics its own field? Four structural reasons — they will echo through every lecture:</p>
    <ul>
      <li><strong>Closed loop.</strong> The policy's outputs change its future inputs. Errors compound; i.i.d. evaluation is meaningless; success is measured by <em>executing</em> in the world, not by held-out loss.</li>
      <li><strong>No internet of robot data.</strong> Vision and NLP ride on billions of free web examples. There is no comparable corpus of robot sensorimotor experience; data must be generated by teleoperation, by simulation, or by the robot's own (risky, slow) trial and error. <em>The data problem is the central economic fact of the field</em> — most of L6–L11 is downstream of it.</li>
      <li><strong>Physical cost and safety.</strong> A bad gradient step in an LLM wastes compute; a bad action on hardware breaks the robot or worse. Exploration is not free.</li>
      <li><strong>Real time, partial observability, embodiment diversity.</strong> Policies must run at control rates on onboard compute, from incomplete observations, across robots with different bodies ("embodiments").</li>
    </ul>

    <h3><span class="knum">1.3</span>The paradigm map</h3>
    <p>Everything in the next eleven weeks fits one taxonomy. Where does the supervision signal come from?</p>
    <div class="cmp-scroll"><table class="cmp">
      <tr><th>Paradigm</th><th>Signal</th><th>Core strength</th><th>Core weakness</th><th>Lecture</th></tr>
      <tr><td><strong>Model-based control</strong></td><td>Physics equations</td><td>Precision, guarantees</td><td>Needs accurate models; brittle in the open world</td><td>L2</td></tr>
      <tr><td><strong>Imitation learning</strong></td><td>Expert demonstrations</td><td>Simple, stable training; safe</td><td>Capped at expert quality; distribution shift; demos are expensive</td><td>L3</td></tr>
      <tr><td><strong>Reinforcement learning</strong></td><td>Reward function</td><td>Can exceed any expert; discovers novel behavior</td><td>Sample-hungry; reward design; exploration risk</td><td>L4–L5</td></tr>
      <tr><td><strong>Offline RL</strong></td><td>Reward labels on a fixed dataset</td><td>RL's optimization without online risk</td><td>Can't query actions outside the data (extrapolation error)</td><td>L5</td></tr>
      <tr><td><strong>Foundation models / VLAs</strong></td><td>Internet pretraining + multi-robot data</td><td>Generalization, language interface, common sense</td><td>Young; evaluation hard; still data-bound</td><td>L7–L10</td></tr>
    </table></div>
    <h4>Pick a paradigm by what supervision you have</h4>
    <p>The table above is really a decision procedure. Robot learning isn't a menu you pick from by taste — the <em>kind of supervision signal you can get</em> forces the choice. Answer the questions below and watch the tree route you to the paradigm (and the lecture) that fits. The point isn't the answer; it's internalizing the questions, because every real project starts here.</p>
    <ParadigmWidget />

    <p>And the historical arc you should keep in your head — the field's "three eras" (you'll hear the guest lecturer Ted Xiao frame it this way in week 7): <strong>(1)</strong> task-specific learned components inside classical stacks, <strong>(2)</strong> end-to-end policies per robot/task family trained by IL or RL, <strong>(3)</strong> the current bet — <em>robot foundation models</em>: one large model, many robots, many tasks, fueled by internet-scale pretraining. The course's title is literally this arc.</p>

    <div class="callout"><span class="co-label">Why now? The three converging forces</span>
    <strong>Priors:</strong> vision-language models supply semantic understanding robots could never learn from their own data alone. <strong>Data:</strong> large multi-robot demonstration corpora (e.g. Open X-Embodiment) and cheap teleoperation rigs. <strong>Architectures &amp; recipes:</strong> transformers and diffusion models turned out to fit action generation beautifully (L6–L7). The 2022–2026 explosion this course documents is these three arriving together.</div>

    <div class="bridge">
      <div class="bridge-title">Bridge · From your background</div>
      <div class="bridge-row"><div class="from"><b>Train/test split, generalization gap</b></div><div class="arrow">→</div><div class="to"><b>Open-world deployment</b>: the "test set" is reality, it's non-stationary, and the agent's own actions generate it</div></div>
      <div class="bridge-row"><div class="from"><b>Feature engineering → deep learning</b> (the ML story you lived through)</div><div class="arrow">→</div><div class="to"><b>Pipeline engineering → end-to-end policies</b>: the same transition, one decade later, with motors attached</div></div>
      <div class="bridge-row"><div class="from"><b>Model risk</b>: a pricing model misused outside its data</div><div class="arrow">→</div><div class="to"><b>Distribution shift on hardware</b>: a policy queried outside its training distribution — same failure, faster consequences</div></div>
    </div>

    <h3><span class="knum">1.4</span>Orientation for the rest of the course</h3>
    <p>Two habits to adopt now. First, for every method you meet, ask the taxonomy questions: <em>What's the supervision signal? On-policy or off? Model-free or model-based? What breaks it?</em> Second, track the data story: nearly every architectural choice in L6–L10 (action chunking, diffusion heads, tokenization, VLM backbones) is ultimately an answer to "how do we squeeze more competence from scarce robot data?"</p>

    <Quiz lecture="l1" />

    <div class="resources">
      <div class="res-head">Lecture 1 resources</div>
      <ul>
        <li><span class="rtag">Slides</span><a href="https://cvg.ethz.ch/lectures/Robot-Learning/lectures/lecture1_intro.pdf" target="_blank" rel="noopener">lecture1_intro.pdf</a></li>
        <li><span class="rtag">Recording</span><a href="https://video.ethz.ch/lectures/d-infk/2026/spring/263-5911-00L/v/AS1N0xMxWTe" target="_blank" rel="noopener">ETH video portal — Lecture 1</a> · <a href="https://www.youtube.com/playlist?list=PLPU18BnWYUZJx3_d901-GD6BGpeWwE2vx" target="_blank" rel="noopener">YouTube playlist</a></li>
        <li><span class="rtag">Homework</span><a href="https://github.com/mees-robot-learning-course/ethz-course-2026/tree/main/hw1_pytorch_tutorial" target="_blank" rel="noopener">HW1: PyTorch &amp; NumPy tutorial</a> — do it even if PyTorch is familiar; it calibrates you to the course's conventions</li>
      </ul>
    </div>

    <CompleteBar id="l1" prev="primer" next="l2" prevLabel="← PRIMER" nextLabel="NEXT: L02 →" @navigate="$emit('navigate', $event)" />
  </section>
</template>

<script setup>
import { ref, onMounted, nextTick } from 'vue';
import Quiz from '../components/Quiz.vue';
import ParadigmWidget from '../widgets/ParadigmWidget.vue';
import CompleteBar from '../components/CompleteBar.vue';
import { renderMath } from '../composables/useKaTeX.js';
import { applyXref } from '../composables/useXref.js';

defineEmits(['navigate']);

const rootEl = ref(null);

onMounted(async () => {
  await nextTick();
  if (rootEl.value) {
    renderMath(rootEl.value);
    applyXref(rootEl.value);
  }
});
</script>
